language: node_js
node_js:
  - 8
script:
  - npm install
before_deploy:
  - bash package.sh
deploy:
  provider: releases
  api_key:
    secure: Xg3Ju8R9VaZYChPkoz/MVij/RH0/6vSEc1I0SbxwhrVSIO8K01QXFPwKk+AF+eAl5qsNnDZgdS63h+6v4AUG9EMpP15NnI/+FPNeYjnBAB5TSXjvNGdcFLn3E4q4GpIFq4hoI1n7PjPYgJIosWGI3OdO7XO1H0o16+xmWWWGCYaqOrMNvUg2pqSdAkrzqAyeuIQ2rk5Uce4E3545DzgI5UcRkVkD3KRBfgdbwBkAMpfG6RbkG8jbjrYjoD3DsjkuZQscOgSj1o2z3HvcFJkChSvEfxMUnn0tyIrwxzcrBhne7Rzqe/SQg/Wwj5F4dv1qN7XCRJsqOFC80ggYWqSeoin8ajFm6XINaw6h5OgsybIEUsrmJxMYkbwGxkRxsLNJ8WOq9hDHaBNy34y8woIWO3rD7VLHcUUd/OCZ9t2/ZlfkcCsFcFaq3LDwV52hCiawSA9IEMAIhbvTcfZ/iySz3bspvlG/MofBIKV7eYdd2OAyWh26vgsA9d0MYUf/wKVlFT83qHXNNUOl8KspUGEb3RG7zKhCLQn8iiEYRqrdMJmULDx1wy3oRooZPi7Br/hhJtMxMoHXU8q+lgTrQzdmBTJ3a/yb6So8CzQ01r8tbykBVhR89AAfQb/MGaNZIDgMBmHDQGPl296qqCVZZnleKDoZQffjt/8VsoskL7u6DwM=
  file: voice-addon-0.0.1.tgz
  skip_cleanup: true
  on:
    repo: andrenatal/voice-addon
    tags: true
    branch: master
